In [ ]:
1. Немного статистики

In [5]:
import numpy as np

np_arr = np.fromstring(open("input.txt", "r").read(), dtype=int, sep=" ")
print("{:.2f} {:.2f} {:.2f}".format(np.median(np_arr), np.mean(np_arr), np.std(np_arr)))

6104.00 5442.20 2612.10


In [3]:
import csv
import numpy as np

with open('input.csv', newline='') as csvfile:
    np_arr = np.array(list(csv.reader(csvfile)))

np_arr = np_arr.transpose().astype(int)

freq_green = np.sum(np_arr[0])
freq_lgreen = np.sum(np_arr[1])
freq_leafgreen = np.sum(np_arr[2])

max_ind  = 1 if (freq_green > freq_lgreen and freq_green > freq_leafgreen) else 2 if (freq_lgreen > freq_leafgreen and freq_lgreen > freq_green) else 3
print (max_ind)

[[14 47 96 11 94 47 19 13 91 36]
 [17 22 61 16 70 43 36 50 25 22]
 [27 76 39 12 82 81 42 41 40 12]]
1


In [ ]:
Задача 4. Очистка логов

In [12]:
import csv
import numpy as np

with open('input.csv', newline='') as incsvfile:
    np_arr = np.genfromtxt(incsvfile, delimiter=',')

for i in range(30):
    for j in range(12):
        if (i%2 != 0 and j % 2 == 0) or (i%2 == 0 and j % 2 != 0):
            np_arr[i][j] /= 2

with open('output.csv', 'w') as outcsvfile:
    np.savetxt(outcsvfile, np_arr, delimiter=",", fmt="%g")